version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    expose:
      - "53/tcp"
      - "53/udp"
      - "67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80/tcp"
    environment: # assign your own values here
      TZ: ${SERVER_TZ}
      WEBPASSWORD: ${WEBPASSWORD}
      ServerIP: ${SERVER_IP}
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    networks:
      default:
        ipv4_address: 172.19.0.10 # any free address on your docker network
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
  doh-server:
    image: satishweb/doh-server:latest
    container_name: doh-server  
    expose:
      - "8053"
    environment:
      UPSTREAM_DNS_SERVER: "udp:172.19.0.10:53" #should match pihole's container ipv4_address
      DOH_HTTP_PREFIX: "/dns-query"
      DOH_SERVER_LISTEN: ":8053"
      DOH_SERVER_TIMEOUT: "10"
      DOH_SERVER_TRIES: "3"
      DOH_SERVER_VERBOSE: "false"
    volumes:
      - ./doh-server.conf:/server/doh-server.conf
    depends_on:
      - pihole
networks: # needed if you use already created docker network
  default:
    external:
      name: your-docker-network
